# Generated by Django 5.2.2 on 2025-06-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True, help_text="Comma-separated list of user skills, e.g. 'python,django,react'"),
        ),
    ]
